# Generated by Django 4.1.7 on 2023-02-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_category_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
