# Generated by Django 4.1.7 on 2023-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_delete_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Профессии',
                'verbose_name_plural': 'Профессия',
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Люди', 'verbose_name_plural': 'Люди'},
        ),
    ]
