# Generated by Django 4.1.7 on 2023-02-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_human_options_alter_profession_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Register.profession', verbose_name='Профессии'),
        ),
    ]
